name: building blocks

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: failed step
        run:  |
          echo "this step will fail"
          exit 1
      - name : say Goodbye
        run: echo "Goodbye, World!"