name: using expressions
run-name: Using Expressions | DEBUG - $((inputs.debug && 'ON' || 'OFF'))

on:
  workflow_dispatch:
    inputs:
        debug:
            type: boolean
            default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[Debug] print start-up data'
      if: inputs.debug
        run: |
          echo "debug mode is ON"
          echo "workflow name: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
      - name: '[Debug] Print when triggered from main'
        if: inputs.debug && github.ref == 'main'
        run: |
          echo "This workflow was triggered from the main branch"
      - name: greetings
        run:  |
          echo "Hello, ${{ github.actor }}! Welcome to the using expressions workflow."
          echo "Debug mode is $((inputs.debug && 'ON' || 'OFF'))"
          
