name: workflow events

on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  echo:
      runs-on: ubuntu-latest
      steps:
        - name: show the trigger
          run: echo "This workflow was triggered by a(n) ${{ github.event_name }} event."